/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SRCGA;

import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;

/**
 *
 * @author heathen
 * 
 * 
 * STOP! We will be replacing this with a skeleton generated by SceneBuilder2 do not put any work in here
 * until we label everything in BuildMode.fxml and then generate the skeleton file.
 */
public class BuildModeController implements Initializable {
    
    /*
    This exposes the label control with the property fx:id="AttributeNaturalBody" defined in our fxml file
    to our java code. Without this line we would not be able to reference the label control in the fxml file.    
    */
    @FXML
    public Label AttributeNaturalBody;

    /*
    This exposes the onaction event that is triggered by a button defined in our fxml file to our java code.
    Without this line the program would not know where to pass the button action event. AttributeBodyLeftArrowButtonClicked
    is referenced in our fxml file as the target of an event on the button.
    */
    @FXML
    private void AttributeBodyLeftArrowButtonClicked(ActionEvent event) {
        //int i = Integer.parseInt(AttributeNaturalBody.getText());
        //i=i-1; //i-- crashes? something in here crashes only on android
        //AttributeNaturalBody.setText(String.valueOf(i));
    }
    
    // same as above for a different button
    @FXML
    private void AttributeBodyRightArrowButtonClicked(ActionEvent event) {
        int i = Integer.parseInt(AttributeNaturalBody.getText());
        i++;
        AttributeNaturalBody.setText(String.valueOf(i));
    }
    
    @FXML
    private void AttributeAgilityLeftArrowButtonClicked(ActionEvent event) {

    }

    /*
    
    We need an event handler for every input control that is defined in our fxml file. Example:
    
    @FXML
    private void AttributeBodyRightArrowButtonClicked(ActionEvent event) {
        do stuff
    }
    
    We need a public declaration for every output control in our fxml file. example: 
    
    @FXML
    public Label AttributeNaturalBody;
    
    Because there will be possibly hundreds of these, we must use an accurate naming convention
    that can easily be understood and sets each one apart from the others.
    
    */
    
    
    
    // ingore this for now
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        
    }    
    
}
